In [8]:
%matplotlib inline
import numpy as np
from matplotlib import pyplot as plt
from scipy.special import expit
from experiment_random import *
from tqdm import tqdm
from tensorflow import set_random_seed
import tensorflow as tf

In [20]:
# Helpers test
assert(norm1([1,1,1]) == 3.0, "Norm1 test")
assert(norm2([1,1,1]) == 3.0 ** 0.5, "Norm2 test")
assert(dot_abs([1,2,3], [-1,-2,3]) == 1 + 4 + 9, "Dot abs test")
assert(norm1_minus_dot_abs([1,2,3],[-1,-2,3]) == 36 - 14, "Norm1 minus dot_abs test")
with tf.Session() as sess:
    assert(np.allclose(expit(4 * 3.14 * 0.1), get_custom_activation(3.14)(0.1).eval()))

In [91]:
np.random.seed(42)
layers = [2, 3, 4]
experiment = RandomExperiment(N = layers, P = 0.1, KLips = 0.1, do_print = True)

Creating network for 2-dimensional input and 4-dimensional output, with 1 hidden layers


In [92]:
w1 = experiment.W[0]
w2 = experiment.W[1]
b1 = experiment.B[0]
b2 = experiment.B[1]

In [93]:
np.random.seed(42)
x = np.random.randn(1, layers[0])

In [94]:
experiment.model_no_dropout.predict(x)

array([[0.41819113, 0.2520001 , 0.2819485 , 0.5752469 ]], dtype=float32)

In [95]:
expit(4 * experiment.K * (expit(4 * experiment.K * (x @ w1 + b1)) @ w2 + b2))

array([[0.41819114, 0.25200011, 0.2819485 , 0.57524691]])

In [96]:
np.random.seed(42)
set_random_seed(42)
experiment.model.predict(x)

array([[0.40944374, 0.22986974, 0.2621686 , 0.5838267 ]], dtype=float32)